### ISSUE TITLE
可以把你的尝试更详细的过程也放上来吗？

### ISSUE THREAD

**Issue by buzhangjiuzhou** [sceext2/fm01#1]
这个项目看起来很有意思，想看看你的进展，以及目前的半成品是什么样子的，所以作者是否可以把目前的一些可以放上来的东西放上来？

**Comment by sceext2** [comment]
这个项目只是把业余做的一些东西放出来, 不过进度确实较慢.  
不过根据胖蚊子系列开源的原则, 相关硬件设计 (原理图, PCB 布局), 软件 (程序代码), 以及文档, 基本都会随时更新.  
目前确实没做多少东西, 也就没多少可以放出来啦 ~

**Comment by buzhangjiuzhou** [comment]
嗯嗯，谢谢！
